[package]
name = "timestamp-prefix"
version = "1.0.0"
edition = "2024"
repository = "https://github.com/veyh/timestamp-prefix"

[dependencies]
anyhow = "1.0.83"
clap = { version = "4.3.5", features = ["derive", "env", "unicode"] }
time = { version = "0.3", features = ["macros", "formatting", "local-offset"] }

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
